# Generated by Django 3.1.1 on 2020-09-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('group_name', models.CharField(max_length=200)),
                ('group_join_rate', models.IntegerField(default=0)),
                ('group_join_avg_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_uid', models.CharField(max_length=200)),
                ('player_name', models.CharField(max_length=200)),
                ('player_total_score', models.IntegerField(default=0)),
                ('player_join_num', models.IntegerField(default=0)),
                ('player_join_rate', models.IntegerField(default=0)),
                ('player_group_id', models.IntegerField(default=0)),
            ],
        ),
    ]
