# Generated by Django 3.1.1 on 2020-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_group_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_total_game_time',
            field=models.IntegerField(default=0),
        ),
    ]
