# Generated by Django 3.1.1 on 2020-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_player_player_total_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='match_id',
            field=models.CharField(default='20200101', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='match_id',
            field=models.CharField(default='20200101', max_length=20),
        ),
    ]
