# Generated by Django 3.1.1 on 2020-09-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200908_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_join_avg_score',
            new_name='group_avg_score',
        ),
    ]
