# Generated by Django 3.1.1 on 2020-09-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200908_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(default='20200101', max_length=20)),
            ],
        ),
    ]
